KB-21-4 Add extention function to File class to write Word
Ansya/kotlinBasic pull request #104
Opened 2024-02-28 08:34 UTC by Ansya

2024-02-28 08:36 UTC, Ansya commented
Иван, по задаче надо было добавлять слова в начало файла. Но я не нашла возможности как это делать. 
Ни функции которая переводит файл в начало, ни функции записи в начало.
Подскажи, пожалуйста, как это делать.

2024-02-28 16:41 UTC, ievetrovdev requested changes

2024-02-28 16:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson_21_task_4.kt
> +    val line = "${word.original}|${word.translate}|${word.correctAnswersCount}"
Как решение читать фаил в строку и к ней добавлять новый текст

2024-02-29 16:49 UTC, ievetrovdev approved these changes

2024-03-01 11:51 UTC, merged