KB-4-3 favorable conditions for legumes is added
Ansya/kotlinBasic pull request #18
Opened 2023-11-28 12:14 UTC by Ansya

2023-11-29 01:48 UTC, ievetrov requested changes

2023-11-29 01:48 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val FAVORABLE_SEASON = "summer"
"Не зима" еще не значит лето) интересный вариант, но давай все же отталкиваться от условий задачи

2023-11-30 13:31 UTC, ievetrov requested changes

2023-11-30 13:31 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +                (airHumidity == FAVORABLE_AIR_HUMIDITY) && FAVORABLE_SEASONS.contains(season)}"
Оригинальное решение использовать функцию .contains(), но представь, что это были бы не 4 сезона, а скажем 12 месяцев, не очень удобно прописывать их все в константу, Тут всего 2 варианта - зима и не зима)

2023-12-02 08:54 UTC, ievetrov requested changes

2023-12-02 08:54 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val FAVORABLE_SEASON_IS_SUMMER = true
По условию все же:
> И типами данных - boolean, boolean, int, String.

UNFAVORABLE_SEASONS = "winter"
А ниже просто проверить на неравенство

2023-12-02 10:41 UTC, ievetrov requested changes

2023-12-02 10:41 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val FAVORABLE_SEASON_IS_SUMMER = true
По условию последнее значение – строка

2023-12-02 10:41 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val FAVORABLE_SEASON_IS_SUMMER = true
Далее в условии нужно применить оператор, который исключает прописанное время года (не зима..)

2023-12-03 11:24 UTC, Ansya commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val FAVORABLE_SEASON_IS_SUMMER = true
дааа - наконец дошло )))
иногда задачи делаю вместе с помощниками (

2023-12-03 13:47 UTC, ievetrov approved these changes
верно!

2023-12-04 11:18 UTC, merged