KB-4-4 Exercises plan added
Ansya/kotlinBasic pull request #19
Opened 2023-11-29 11:12 UTC by Ansya

2023-11-29 11:14 UTC, Ansya commented
Я тут немного запуталась с комитами. Случайно сначала в мейн отправила. Потом хотела сделать реверт, но не запушила. Вышла такая вот каша )
не нашлась как исправить. Буду рада совету!

2023-11-30 15:06 UTC, ievetrov requested changes

2023-11-30 15:06 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +        println(exersisesPlan.format(!exerciseForHands, !exerciseForLags, !exerciseForBack, !exerciseForPress))
Верный ход, но давай оптимизируем. Предлагаю четность (и только ее) числа сохранять в отдельный Boolean "флаг", например isEven. И применять его уже при выводе “как есть” или с отрицанием (инвертируя значение).

Таким образом избавимся от повторений вызова принта

2023-11-30 15:06 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val exerciseForPress = true
этим флагом можно проинициализировать эти переменные. значения по умолчанию думаю тут будут лишние

2023-11-30 15:09 UTC, ievetrov commented
> Я тут немного запуталась с комитами. Случайно сначала в мейн отправила. Потом хотела сделать реверт, но не запушила. Вышла такая вот каша ) не нашлась как исправить. Буду рада совету!

немного сложновато восстановить события не зная что именно было сделано) но сейчас если пушить исправления в ту же рабочую ветку - пулл реквест станет актуальным, изменения подтянутся

2023-12-01 10:49 UTC, Ansya commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val exerciseForPress = true
да так код стройнее, спасибо за замечание.
надеюсь правильно поняла )

2023-12-02 09:43 UTC, ievetrov approved these changes

2023-12-03 11:24 UTC, merged