Lesson4 task5
Ansya/kotlinBasic pull request #20
Opened 2023-11-29 11:51 UTC by Ansya

2023-11-29 12:01 UTC, Ansya commented
разобралась в итоге. Надо было мейн запушить перед созданием новых бранчей. 
следующий комит будет без этого реверта

2023-11-30 15:14 UTC, ievetrov requested changes

2023-11-30 15:14 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +                        (boxesProvisionNumber >= BOXES_PROVISIONS_NUMBER)
По условию в этом случае провизии должно быть более 50 ящиков

2023-11-30 15:14 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    println(
и получилось довольно размашесто, думаю можно чуть компактнее)

<img width="920" alt="Снимок экрана 2023-11-30 в 19 12 42" src="https://github.com/Ansya/kotlinBasic/assets/34489023/919edd6f-a3d5-4b95-8b11-504d5e69d7a8">

2023-12-02 09:44 UTC, ievetrov approved these changes

2023-12-03 11:24 UTC, merged