KB-5-1 authorisation module added
Ansya/kotlinBasic pull request #21
Opened 2023-11-30 11:36 UTC by Ansya

2023-12-01 01:21 UTC, ievetrov requested changes
Технически все верно (даже почти идеально), но есть небольшая придирка

2023-12-01 01:21 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val secondValue = (0..100).random()
Можно вынести range в переменную

2023-12-02 10:06 UTC, ievetrov requested changes

2023-12-02 10:06 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +val VALUES_RANGE = 0..100
я написал именно "переменную", а не константу не случайно. тут получилось несколько разных ошибок в кучу

1. стиль VALUES_RANGE для констант, а ты объявила обычную переменную (без ключевого слова const)
2. соответственно вынесла не константу за пределы метода (не обязательно)
3. фундаментальное: если ты в текущем коде проставишь к переменной const будет ошибка "Const 'val' has type 'IntRange'. Only primitives and String are allowed". В качестве констант возможны только примитивы. 

Почему так и зачем вообще нужны константы? 
В Kotlin использование констант обеспечивает улучшение производительности за счет процесса инлайнинга. Захардкоженные значения, определенные как константы, внедряются напрямую в код во время компиляции, минимизируя издержки на выполнение времени выполнения и создавая код с фиксированными значениями.

2023-12-04 11:23 UTC, Ansya commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +val VALUES_RANGE = 0..100
спасибо за подробное пояснение. Уяснила

2023-12-04 22:00 UTC, ievetrov approved these changes
Отлично!

2023-12-05 10:39 UTC, merged