KB-5-5 Lottery improvements added
Ansya/kotlinBasic pull request #25
Opened 2023-12-05 09:49 UTC by Ansya

2023-12-05 13:08 UTC, ievetrov requested changes

2023-12-05 13:08 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_5.kt
> +    val (sugestedValue1, sugestedValue2, sugestedValue3) = readLine()!!.split(' ')
1) Давай использовать readln(), чтобы не заморачиваться с нулябельнойстью
2) А зачем делать деструктуринг (я про перечисление переменных), а потом формировать из них список? Можно же применить маппинг к результату split()

2023-12-05 13:08 UTC, ievetrov commented on src/main/kotlin/lesson_5/lesson_5_task_5.kt
> +    val valuesToWin = listOf(valuesRange.random(), valuesRange.random(), valuesRange.random())
Тут можно сократить, используя конструкцию:
```Kotlin
List(3) { valuesRange.random() }
```

2023-12-06 04:53 UTC, Ansya commented on src/main/kotlin/lesson_5/lesson_5_task_5.kt
> +    val (sugestedValue1, sugestedValue2, sugestedValue3) = readLine()!!.split(' ')
Хорошая идея - но я не все возможности еще изучила. 
Хорошо когда есть старший наставник

2023-12-06 14:26 UTC, ievetrovdev approved these changes

2023-12-07 04:35 UTC, merged