KB-6-2 timer is added
Ansya/kotlinBasic pull request #27
Opened 2023-12-06 05:09 UTC by Ansya

2023-12-06 17:09 UTC, ievetrov requested changes

2023-12-06 17:09 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_6.kt
> +    while (secNumber-- > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2023-12-07 04:39 UTC, Ansya commented on src/main/kotlin/lesson_6/lesson_6_task_6.kt
> +    while (secNumber-- > 0) {
да конечно ))
А я прочла задачу, пыталась ее с темой соотнести и найти заковыристое решение

2023-12-07 10:45 UTC, ievetrovdev approved these changes

2023-12-07 11:08 UTC, merged