KB-7-5 Strong password generator added.
Ansya/kotlinBasic pull request #35
Opened 2023-12-07 11:54 UTC by Ansya

2023-12-10 09:53 UTC, ievetrov requested changes

2023-12-10 09:53 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +//    for (i in passwordSize downTo 1) {
закомменченный код как правило бесполезен

2023-12-10 09:53 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +        val element = passwordElementsRange.random()
тут получается довольно сложная логика, можно просто создать один рейнж, суммировав их:
 ('a'..'z') + ('A'..'Z') + ('0'..'9')

И уже из финального ренжа брать рандомный символ

2023-12-10 10:30 UTC, Ansya commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +        val element = passwordElementsRange.random()
🙃 как все просто оказывается. супер!

2023-12-11 19:05 UTC, ievetrov requested changes

2023-12-11 19:05 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +        password += rangeForPassword.random().toString()
А для чего .toString() ?

2023-12-12 10:53 UTC, Ansya commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +        password += rangeForPassword.random().toString()
хороший вопрос - лишний конечно

2023-12-12 11:15 UTC, ievetrov approved these changes
Хорошо

2023-12-12 11:18 UTC, merged