KB-8-1 Counter of ad views per week added
Ansya/kotlinBasic pull request #36
Opened 2023-12-08 04:58 UTC by Ansya

2023-12-09 13:06 UTC, ievetrovdev requested changes

2023-12-09 13:06 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson_8_task_1.kt
> +    for (adViews in numberOfAdViews) {
Рабочий вариант подсчета, но советую попробовть использовать функцию sum()

2023-12-09 13:06 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson_8_task_1.kt
> +    println("Number of ad views per week $numberOfAdViewsPerWeek")
Попробуй вывести не только общее количество, но еще и весь остальной массив

2023-12-10 10:50 UTC, Ansya commented on src/main/kotlin/lesson_8/lesson_8_task_1.kt
> +    for (adViews in numberOfAdViews) {
ok, хорошая идея )

2023-12-11 15:27 UTC, ievetrov approved these changes

2023-12-12 11:07 UTC, merged