KB-8-5 Creating the list of recipe ingredients is added
Ansya/kotlinBasic pull request #40
Opened 2023-12-10 10:43 UTC by Ansya

2023-12-10 11:32 UTC, ievetrovdev requested changes

2023-12-10 11:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson_8_task_5.kt
> +    val arrayOfIngredients = arrayOfNulls<String>(numberOfIngredientsInRecipe)
Все корректно!
А еще можно сразу объявлять и инициализировать массив через лямбду
val array = Array(readln().toInt()) { readln() }

Попробуй применить этот код и посмотреть как он работает.

2023-12-10 11:35 UTC, Ansya commented on src/main/kotlin/lesson_8/lesson_8_task_5.kt
> +    val arrayOfIngredients = arrayOfNulls<String>(numberOfIngredientsInRecipe)
обалдеть какое красивое решение! Спасибо
Лямбды конечно еще не смотрела - это такие тонкости )))

2023-12-11 15:29 UTC, ievetrov approved these changes

2023-12-12 11:07 UTC, merged