KB-9-1 recipe ingredients in List added
Ansya/kotlinBasic pull request #41
Opened 2023-12-11 10:42 UTC by Ansya

2023-12-11 19:21 UTC, ievetrovdev requested changes

2023-12-11 19:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +        println("${listOfIngredients.indexOf(ingredient) + 1}) $ingredient")
Избыточная и не оптимизировання конструкция. indexOf это по сути for что значит пробегает весь массив. нужно избегать for в for когда это возможно

2023-12-12 11:13 UTC, Ansya commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +        println("${listOfIngredients.indexOf(ingredient) + 1}) $ingredient")
спасибо поняла

2023-12-13 13:27 UTC, ievetrov approved these changes

2023-12-14 10:22 UTC, merged