KS-1-5 Time spent by Yuri Gagarin in space is added
Ansya/kotlinBasic pull request #5
Opened 2023-11-19 11:06 UTC by Ansya

2023-11-19 14:31 UTC, ievetrov requested changes

2023-11-19 14:31 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("Time spent by Yuri Gagarin in space is %02d".format(hours)
отлично, можно даже еще аккуратнее сделать (только с твоим же текстом)
println("%02d:%02d:%02d".format(hours, minutes, seconds))

2023-11-19 14:31 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    minutes = seconds/60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2023-11-19 14:31 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    minutes = seconds/60
Также напоминаю про форматирование - арифметические знаки обосабливаются пробелами

2023-11-20 21:46 UTC, ievetrov requested changes

2023-11-20 21:46 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +const val secondsInMinute = 60
константы именуются в отличном от обычных переменных стиле)

2023-11-20 21:46 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +const val minutesInHour = 60
достаточно одного значения, оно точно будет неизменно

2023-11-22 11:00 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +const val secondsInMinute = 60
Не поправлено(

Нейминг констант отличен от обычных переменных. В [документации по ссылке](https://developer.android.com/kotlin/style-guide#constant_names) есть более полное описание стайл гайда

2023-11-22 11:01 UTC, ievetrov requested changes
оставил коммент по константам)

2023-11-22 11:02 UTC, ievetrov commented
Кстати, в названии ПРа у тебя префикс "KS-1-5". Все окей, но напомню, что у меня проект назывался KotlinSprint - и это аббревиатура. В твоем случае это могло бы быть KB

2023-11-25 10:12 UTC, Ansya commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +const val secondsInMinute = 60
недоглядела - не засушились изменения )

2023-11-25 15:32 UTC, ievetrov approved these changes
отлично!

2023-11-26 11:22 UTC, merged