KB-12-1 Weather class added
Ansya/kotlinBasic pull request #56
Opened 2024-01-16 10:52 UTC by Ansya

2024-01-17 05:55 UTC, ievetrovdev approved these changes

2024-01-17 05:56 UTC, ievetrovdev requested changes

2024-01-17 05:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson_12_task_1.kt
> +    var precipitation: Boolean = false
булеан переменные принято называть с is или has)

2024-01-17 05:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson_12_task_1.kt
> +class Weather() {
Если в классе пустой основной конструктор — его круглые скобки опускаются

2024-01-18 04:46 UTC, ievetrovdev requested changes

2024-01-18 04:46 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson_12_task_1.kt
> +class Weather() {
забыла пустые скобки убрать)

2024-01-18 18:07 UTC, Ansya commented on src/main/kotlin/lesson_12/lesson_12_task_1.kt
> +class Weather() {
ох ох - да и в правду! Это вроде мелочь, но лишний шум очень даже помогает читаемости

2024-01-19 02:34 UTC, ievetrovdev approved these changes

2024-01-20 13:57 UTC, merged