KB-13-3 Contacts list with companies filter added
Ansya/kotlinBasic pull request #63
Opened 2024-01-20 18:59 UTC by Ansya

2024-01-22 07:26 UTC, ievetrovdev requested changes

2024-01-22 07:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +    val companiesList = contactsList.filter{ it.company != null }.map { it.company }
Да, все отлично. Но попробуй еще `mapNotNull`

2024-01-24 04:29 UTC, Ansya commented on src/main/kotlin/lesson_13/lesson_13_task_3.kt
> +    val companiesList = contactsList.filter{ it.company != null }.map { it.company }
спасибо. класс!
эти функции-расширения для работы с коллекциями - вообще очень интересная штука!

2024-01-24 10:31 UTC, ievetrovdev approved these changes
Да, теперь идеально! ))

2024-01-24 14:23 UTC, merged