KB-14-3 Figures classes added with area and perimeter calculation
Ansya/kotlinBasic pull request #68
Opened 2024-01-24 05:56 UTC by Ansya

2024-01-24 23:30 UTC, ievetrovdev requested changes

2024-01-24 23:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_3.kt
> +    open fun calculateArea() :Int {
- для абстрактных методов можно не описывать тело
- обычно двоеточие ближе к скобкам, чем к возвращаему типу. Давай придерживаться единого стиля

2024-01-26 12:16 UTC, Ansya commented on src/main/kotlin/lesson_14/lesson_14_task_3.kt
> +    open fun calculateArea() :Int {
Иван, можно поподробнее про первый пункт? Как не описывать тело? Тело функции не описывать? да?

2024-01-26 13:18 UTC, Ansya commented on src/main/kotlin/lesson_14/lesson_14_task_3.kt
> +    open fun calculateArea() :Int {
пояла и разобралась сама. спасибо!

2024-01-27 21:04 UTC, ievetrovdev approved these changes
Да, теперь все верно!

> Иван, можно поподробнее про первый пункт? Как не описывать тело? Тело функции не описывать? да?

Ну да, лучше явно подчеркнуть, что требуется объявить тело

2024-02-02 18:23 UTC, merged