KB-15-1 add flying ang swimming creatures
Ansya/kotlinBasic pull request #71
Opened 2024-02-05 09:18 UTC by Ansya

2024-02-06 14:30 UTC, ievetrovdev requested changes
В целом задаче можно было не делать  абстрактные классы и просто использовать интерфейсы для Crucian, Duck и Gull. Но так даже лучше.
Есть мелкие комменты по оформлению (см. ниже)

2024-02-06 14:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_1.kt
> +}
давай добавим пустых строк между интересами, а то немного сливается, если смотреть не в IDEA

2024-02-06 14:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_1.kt
> +    val name :String,
форматирование чуть съехало

2024-02-06 14:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_1.kt
> +    val name :String,
форматирование чуть съехало

2024-02-06 14:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_1.kt
> +    val name :String,
форматирование чуть съехало

2024-02-10 13:09 UTC, ievetrov approved these changes

2024-02-12 05:05 UTC, merged