KB-15-2 sent weather stats to server
Ansya/kotlinBasic pull request #72
Opened 2024-02-05 14:12 UTC by Ansya

2024-02-07 10:33 UTC, ievetrovdev requested changes
Да, решение корректное, есть пара моментов по форматированию (см. ниже)

Кстати, это довольно популярный паттерн, когда на входе у метода базовый тип данных, а внутри в зависимости от конкретного типа, разное поведение. 
Этот паттерн еще называют "Команда": https://refactoring.guru/ru/design-patterns/command

2024-02-07 10:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_2.kt
> +    fun sendStatsToServer(statsValue :WeatherStationStats) {
почему то двоеточие у тебя "гуляет" от PR к PRу ))
Давай ставить его после идентификатора (названия переменной) потом пробел и потом тип данных

2024-02-07 10:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_2.kt
> +        if (statsValue is Temperature) {
давай попробуем использовать when, будет немного компактнее

2024-02-08 14:08 UTC, Ansya commented
> Да, решение корректное, есть пара моментов по форматированию (см. ниже)
> 
> Кстати, это довольно популярный паттерн, когда на входе у метода базовый тип данных, а внутри в зависимости от конкретного типа, разное поведение. Этот паттерн еще называют "Команда": https://refactoring.guru/ru/design-patterns/command

Спасибо Иван, Здорово!
Вот ради таких тонкостей и надо идти к человеку, который уже многое изучил!

2024-02-10 13:15 UTC, ievetrov approved these changes

2024-02-12 05:05 UTC, merged