KB-15-3 add forum admin and forum user
Ansya/kotlinBasic pull request #73
Opened 2024-02-05 14:57 UTC by Ansya

2024-02-07 12:48 UTC, ievetrovdev requested changes
Технически все отлично. Есть вопрос к форматированию

2024-02-07 12:48 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_3.kt
> +) :Member() {
Тут не хватает пробела после двоеточия

А ты пользуешься автоформатированием?
Попробуй в IDEA нажать `Code -> Reformat Code`. 
Там же можешь подсмотреть сочетание клавиш для своей платформы и использовать его перед коммитом

2024-02-08 14:13 UTC, Ansya commented on src/main/kotlin/lesson_15/lesson_15_task_3.kt
> +) :Member() {
> Тут не хватает пробела после двоеточия
> 
> А ты пользуешься автоформатированием? Попробуй в IDEA нажать `Code -> Reformat Code`. Там же можешь подсмотреть сочетание клавиш для своей платформы и использовать его перед коммитом

Форматирование у меня пока очень страдает. Нет внимания к этому вопросу. Хотя если я сама увижу код на Свифт плохо отформатированный буду ругаться про себя ))) 
Я буду внимательней! Спасибо что подсвечиваешь.

2024-02-10 13:16 UTC, ievetrov approved these changes

2024-02-12 05:06 UTC, merged