KB-17-1 quiz element added
Ansya/kotlinBasic pull request #81
Opened 2024-02-14 15:07 UTC by Ansya

2024-02-15 14:50 UTC, ievetrovdev requested changes

2024-02-15 14:50 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson_17_task_1.kt
> +fun main() {
все хорошо, только давай сделаем автоформатирование

2024-02-16 04:44 UTC, Ansya commented on src/main/kotlin/lesson_17/lesson_17_task_1.kt
> +fun main() {
Ой да - это мой бич ))

2024-02-17 12:58 UTC, ievetrovdev approved these changes

2024-02-18 03:47 UTC, merged