KB-19-2 Category of goods enum class added
Ansya/kotlinBasic pull request #92
Opened 2024-02-21 07:47 UTC by Ansya

2024-02-21 17:10 UTC, ievetrovdev requested changes

2024-02-21 17:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +    CLOTHES {
Та же проблема, но тут можно не создавать абстрактный класс, а создать один обычный, который будет возвращать текст

2024-02-22 07:07 UTC, Ansya commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +    CLOTHES {
Иван, я сделала как для первой задачи. Немного не поняла про предложение создать обычный класс, который будет возвращать текст. Можно пример?

2024-02-22 19:25 UTC, ievetrovdev approved these changes
Как вариант, можно делать так, а не писать в каждом элементе свой метод

2024-02-22 19:25 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +    OTHER("разное"),
```
enum class Category {
    CLOTHING, STATIONERY, MISC;

    fun getCategoryName() = when(this) {
        CLOTHING -> "Одежда"
        STATIONERY -> "Канцелярские товары"
        MISC -> "Разное"
    }
}
```

2024-02-23 09:45 UTC, Ansya commented on src/main/kotlin/lesson_19/lesson_19_task_2.kt
> +    OTHER("разное"),
спасибо поняла! Как много вариантов все же и как красиво!

2024-02-23 09:46 UTC, merged