KB-19-4 Tank class added with 3 types of patrons
Ansya/kotlinBasic pull request #94
Opened 2024-02-21 11:15 UTC by Ansya

2024-02-21 17:17 UTC, ievetrovdev requested changes

2024-02-21 17:17 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +    abstract fun getTypeName() : String
Зачем тут вообще нужен это метод, надо или убрать или использовать. Если хочешь использовать, то стоит передать решение на один общий метод

2024-02-22 07:09 UTC, Ansya commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +    abstract fun getTypeName() : String
Кажется я поняла тебя. Надеюсь )))

2024-02-22 19:28 UTC, ievetrovdev approved these changes

2024-02-22 19:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +        return when (strikeForce) {
Да, почти, только можно используя this сразу к объекту обращаться

  ```
  fun getTypeName() : String {
        return when (this) {
            BLUE -> "синий"
            GREEN -> "зеленый"
            RED -> "красный"
            NONE -> "<не заряжен>"
        }
    }
```

2024-02-23 09:48 UTC, Ansya commented on src/main/kotlin/lesson_19/lesson_19_task_4.kt
> +        return when (strikeForce) {
спасибо - столько вариантов. Запомню

2024-02-23 10:46 UTC, merged