KB-20-4 Lambda function for pressing elements is added
Ansya/kotlinBasic pull request #99
Opened 2024-02-24 08:57 UTC by Ansya

2024-02-24 16:48 UTC, ievetrovdev requested changes

2024-02-24 16:48 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val pressElement: (String) -> Unit = {
Сейчас преобразуешь в пару элементов, надо только список лямбд

2024-02-24 16:48 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    elementsMap.forEach{
Не хватает вывод только четных элементов

2024-02-26 08:06 UTC, Ansya commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    elementsMap.forEach{
Иван, надеюсь я правильно поняла. 
Если нет - буду рада дополнительному объяснению.

2024-02-26 16:38 UTC, ievetrovdev requested changes

2024-02-26 16:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val elementsMap = elementList.map { it to pressElement() }
четные элементы правильно сделано, но преобразование в лямбду не исправлена. Не нужно создавать pressElement, хватит если сразу в elementList.map напишешь вывод строки в консоль.

2024-02-26 16:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +            println("${pair.second} ${pair.first}")
а здесь уже просто будешь вызывать созданную лямбду

2024-02-27 08:20 UTC, Ansya commented on src/main/kotlin/lesson_20/lesson_20_task_4.kt
> +    val elementsMap = elementList.map { it to pressElement() }
я наконец-то поняла!  И как же это красиво!!! очень )

2024-02-27 16:52 UTC, ievetrovdev approved these changes
Отлично! очень хорошо что все понятно стало)

2024-02-28 07:20 UTC, merged